name: ppd430

channels:
  - conda-forge

dependencies:
  - folium
  - geopandas
  - geopy
  - jupyterlab
  - mapclassify
  - numpy
  - osmnx
  - pandas
  - python == 3.*
  - requests
  - seaborn
  - scipy
  - shapely
  - statsmodels
